language: go

go:
  - 1.8

sudo: false

services:
  - docker

install:
  - make setup-ci

before_script:
  - make run-containers
  - make create-es-index-template

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
