language: go

go:
  - 1.8

sudo: false

services:
  - docker

install:
  - make setup-ci

script:
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
