version: '2'

services:
  cassandra:
    image: cassandra:3.11
    container_name: mqtthistory_test_cassandra
    ports:
      - 9042:9042
  mosquitto:
    image: eclipse-mosquitto:1.4.12
    container_name: mqtthistory_test_mosquitto
    ports:
      - "1883:1883"
    environment:
      - DOMAIN=example.local
      - PORT=8080
  mongo:
    container_name: mqtthistory_test_mongo
    image: mongo:3.6.23
    ports:
      - "27017:27017"
