---
healthcheck:
  workingText: "WORKING"
elasticsearch:
  host: "http://localhost:9123"
  sniff: false
  indexPattern: "chat-*"
  indexMappings:
    chat: '{ "mappings": { "message":{}}}'
redis:
  host: "localhost"
  port: 4444
  password: ""
  maxPoolSize: 10
  db: 0
logger:
  level: "debug"
