---
numberOfDaysToSearch: 7
healthcheck:
  workingText: "WORKING"
elasticsearch:
  host: "http://localhost:9123"
  sniff: false
  indexMappings:
    chat: '{ "mappings": { "message":{}}}'
mongo:
  host: "mongodb://localhost:27017"
  allow_anonymous: false
  database: "mqtt"
logger:
  level: "debug"
jaeger:
  disabled: true
  samplingProbability: 0.001
