---
healthcheck:
  workingText: "WORKING"
elasticsearch:
  host: "http://localhost:9123"
  sniff: false
  indexMappings:
    chat: '{ "mappings": { "message":{"_ttl": { "enabled": true, "default": "2d" }}}}'
redis:
  host: "localhost"
  port: 4444
  password: ""
  maxPoolSize: 10
  db: 0
logger:
  level: "debug"
