---
numberOfDaysToSearch: 7
healthcheck:
  workingText: "WORKING"
elasticsearch:
  host: "http://localhost:9123"
  sniff: false
  indexMappings:
    chat: '{ "mappings": { "message":{}}}'
redis:
  host: "localhost"
  port: 4444
  password: ""
  maxPoolSize: 10
  db: 0
mongo:
  host: "mongodb://localhost"
  port: 27017
  allow_anonymous: false
logger:
  level: "debug"
