---
numberOfDaysToSearch: 7
healthcheck:
  workingText: "WORKING"
mongo:
  host: "mongodb://localhost:27017"
  allow_anonymous: true
  database: "chat"
  messages:
    enabled: true
    limit: 10
    collection: "messages"
logger:
  level: "debug"
extensions:
  dogstatsd:
    host: localhost:8125
    prefix: mqtthistory.
    tags_prefix: ""
    rate: 1
    enabled: true
