---
numberOfDaysToSearch: 7
healthcheck:
  workingText: "WORKING"
cassandra:
  hosts: "localhost:9042"
  keyspace: "chat"
  enabled: true
  bucket:
    quantity: 10 # number of buckets to read on a select using limit
  messages:
    limit: 10
mongo:
  host: "mongodb://localhost:27017"
  allow_anonymous: true
  database: "chat"
  messages:
    enabled: true
    limit: 10
    collection: "messages"
logger:
  level: "debug"
jaeger:
  disabled: true
  samplingProbability: 0.001
extensions:
  dogstatsd:
    host: localhost:8125
    prefix: mqtthistory.
    tags_prefix: ""
    rate: 1
    enabled: true
