name: Publish Docker Image

on:
  release:
    types:
      - published
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[abcehlprt]+.?[0-9]?[0-9]?'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: make test

  build-amd64:
    name: Build for linux/amd64
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tfgco/mqtt-history:${{ github.ref_name }}-amd64
          provenance: false

  build-arm64:
    name: Build for linux/arm64
    runs-on: ubuntu-22.04-arm
    needs: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tfgco/mqtt-history:${{ github.ref_name }}-arm64
          provenance: false

  push-manifest:
    name: Push multi-arch manifest
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Inspect images before creating manifest (Debug Step)
        run: |
          echo "--- Inspecting AMD64 image ---"
          docker buildx imagetools inspect tfgco/mqtt-history:${{ github.ref_name }}-amd64
          echo "--- Inspecting ARM64 image ---"
          docker buildx imagetools inspect tfgco/mqtt-history:${{ github.ref_name }}-arm64

      - name: Create and push manifest
        run: |
          docker manifest create tfgco/mqtt-history:${{ github.ref_name }} \
            --amend tfgco/mqtt-history:${{ github.ref_name }}-amd64 \
            --amend tfgco/mqtt-history:${{ github.ref_name }}-arm64
          docker manifest push tfgco/mqtt-history:${{ github.ref_name }}
