name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.8'
      - name: Set up GOPATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-Up CI
        run: make setup-ci
      - name: Run tests
        run: make test
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run github.com/mattn/goveralls -coverprofile coverage-all.out -service=github
